version: '3.9'

services:
  web:
    build: .
    container_name: NexTrace_web
    command: gunicorn config.wsgi:application --config config/gunicorn_config.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: NexTrace_db
    environment:
      POSTGRES_DB: NexTrace
      POSTGRES_USER: NexTrace_user
      POSTGRES_PASSWORD: NexTrace_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: NexTrace_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - web

volumes:
  pgdata:
