version: '3.9'

services:
  web:
    build: .
    container_name: NexTrace_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: NexTrace_db
    environment:
      POSTGRES_DB: NexTrace
      POSTGRES_USER: NexTrace_user
      POSTGRES_PASSWORD: NexTrace_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
