global:
  resolve_timeout: 1m

route:
  receiver: "default"

receivers:
  - name: "default"
    email_configs:
      - to: "seu-email@exemplo.com"
        from: "alertas@monitoramento.local"
        smarthost: "smtp.exemplo.com:587"
        auth_username: "usuario"
        auth_password: "senha"
