name: CI/CD NexTrace

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nextraceweb:latest ./Web

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextraceweb:latest

  vercel:
    name: Deploy no Vercel
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Deploy no Vercel
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --confirm ./Web
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
